select 
    game_id,
    pfr_game_id,
    season::integer,
    week::integer,
    game_type,
    team,
    opponent,
    pfr_player_name,
    pfr_player_id,
    cast(case when def_ints = 'NA' then null else def_ints end as integer) as def_ints,
    cast(case when def_targets = 'NA' then null else def_targets end as integer) as def_targets,
    cast(case when def_completions_allowed = 'NA' then null else def_completions_allowed end as integer) as def_completions_allowed,
    cast(case when def_completion_pct = 'NA' then null else def_completion_pct end as numeric) as def_completion_pct,
    cast(case when def_yards_allowed = 'NA' then null else def_yards_allowed end as integer) as def_yards_allowed,
    cast(case when def_yards_allowed_per_cmp = 'NA' then null else def_yards_allowed_per_cmp end as numeric) as def_yards_allowed_per_cmp,
    cast(case when def_yards_allowed_per_tgt = 'NA' then null else def_yards_allowed_per_tgt end as numeric) as def_yards_allowed_per_tgt,
    cast(case when def_receiving_td_allowed = 'NA' then null else def_receiving_td_allowed end as integer) as def_receiving_td_allowed,
    cast(case when def_passer_rating_allowed = 'NA' then null else def_passer_rating_allowed end as numeric) as def_passer_rating_allowed,
    cast(case when def_adot = 'NA' then null else def_adot end as numeric) as def_adot,
    cast(case when def_air_yards_completed = 'NA' then null else def_air_yards_completed end as integer) as def_air_yards_completed,
    cast(case when def_yards_after_catch = 'NA' then null else def_yards_after_catch end as integer) as def_yards_after_catch,
    cast(case when def_times_blitzed = 'NA' then null else def_times_blitzed end as integer) as def_times_blitzed,
    cast(case when def_times_hurried = 'NA' then null else def_times_hurried end as integer) as def_times_hurried,
    cast(case when def_times_hitqb = 'NA' then null else def_times_hitqb end as integer) as def_times_hitqb,
    cast(case when def_sacks = 'NA' then null else def_sacks end as numeric) as def_sacks,
    cast(case when def_pressures = 'NA' then null else def_pressures end as integer) as def_pressures,
    cast(case when def_tackles_combined = 'NA' then null else def_tackles_combined end as integer) as def_tackles_combined,
    cast(case when def_missed_tackles = 'NA' then null else def_missed_tackles end as integer) as def_missed_tackles,
    cast(case when def_missed_tackle_pct = 'NA' then null else def_missed_tackle_pct end as numeric) as def_missed_tackle_pct
from {{ source('warehouse', 'advstats_def') }}