select
    game_id,
    pfr_game_id,
    season::integer,
    week::integer,
    game_type,
    team,
    opponent,
    pfr_player_name,
    pfr_player_id,
    cast(case when passing_drops = 'NA' then null else passing_drops end as integer) as passing_drops,
    cast(case when passing_drop_pct = 'NA' then null else passing_drop_pct end as numeric) as passing_drop_pct,
    cast(case when receiving_drop = 'NA' then null else receiving_drop end as integer) as receiving_drop,
    cast(case when receiving_drop_pct = 'NA' then null else receiving_drop_pct end as numeric) as receiving_drop_pct,
    cast(case when passing_bad_throws = 'NA' then null else passing_bad_throws end as integer) as passing_bad_throws,
    cast(case when passing_bad_throw_pct = 'NA' then null else passing_bad_throw_pct end as numeric) as passing_bad_throw_pct,
    cast(case when times_sacked = 'NA' then null else times_sacked end as integer) as times_sacked,
    cast(case when times_blitzed = 'NA' then null else times_blitzed end as integer) as times_blitzed,
    cast(case when times_hurried = 'NA' then null else times_hurried end as integer) as times_hurried,
    cast(case when times_hit = 'NA' then null else times_hit end as integer) as times_hit,
    cast(case when times_pressured = 'NA' then null else times_pressured end as integer) as times_pressured,
    cast(case when times_pressured_pct = 'NA' then null else times_pressured_pct end as numeric) as times_pressured_pct,
    cast(case when def_times_blitzed = 'NA' then null else def_times_blitzed end as integer) as def_times_blitzed,
    cast(case when def_times_hurried = 'NA' then null else def_times_hurried end as integer) as def_times_hurried,
    cast(case when def_times_hitqb = 'NA' then null else def_times_hitqb end as integer) as def_times_hitqb
from {{ source('warehouse', 'advstats_pass' )}}