select 
    play_id,
    game_id,
    old_game_id,
    home_team,
    away_team,
    case 
        when season_type = 'REG' then 0
        when season_type = 'POST' then 1
    else
        0
    end as playoffs,
    "week"::numeric::integer as week_of_season,
    posteam as possession_team,
    posteam_type as possession_team_type,
    defteam as defense_team,
    side_of_field,
    yardline_100 as absolute_yardline,
    to_date(game_date, 'YYYY-MM-DD'),
    quarter_seconds_remaining::numeric::integer,
    half_seconds_remaining::numeric::integer,
    game_seconds_remaining::numeric::integer,
    case 
        when game_half = 'Half1' then 'first'
        when game_half = 'Half2' then 'second'
        when game_half = 'Overtime' then 'overtime'
    else
        game_half
    end as game_half,
    quarter_end::numeric::integer as end_of_quarter,
    drive::numeric::integer,
    sp::numeric::integer as scoring_play,
    qtr::numeric::integer,
    down::numeric::integer,
    goal_to_go::numeric::integer,
    "time" as time_remaining_quarter,
    yrdln as yardline_description,
    ydstogo::numeric::integer as yards_to_go,
    ydsnet::numeric::integer as yards_to_go_net,
    "desc" as play_description,
    play_type,
    yards_gained::numeric::integer,
    shotgun::numeric::integer,
    no_huddle::numeric::integer,
    qb_dropback::numeric::integer,
    qb_kneel::numeric::integer,
    qb_spike::numeric::integer,
    qb_scramble::numeric::integer,
    pass_length as pass_length_category,
    pass_location as pass_field_location,
    air_yards::numeric::integer,
    yards_after_catch::numeric::integer,
    run_location,
    run_gap,
    field_goal_result,
    kick_distance::numeric::integer,
    extra_point_result,
    two_point_conv_result as two_point_conversion_result,
    home_timeouts_remaining::numeric::integer,
    away_timeouts_remaining::numeric::integer,
    timeout::numeric::integer as is_timeout,
    timeout_team,
    cast(
        case 
            when timeout_team = home_team then 1
            when timeout_team = away_team then 0
        else
            null
		end
    as integer) as timeout_home,
    cast(
        case
            when timeout_team = away_team then 1
            when timeout_team = home_team then 0
        else
            null
		end
    as integer) as timeout_away,
    td_team,
    td_player_name,
    td_player_id,
    posteam_timeouts_remaining::numeric::integer,
    defteam_timeouts_remaining::numeric::integer,
    total_home_score::numeric::integer as result_home_score,
    total_away_score::numeric::integer as result_away_score,
    posteam_score::numeric::integer as possession_team_score,
    defteam_score::numeric::integer,
    score_differential,
    posteam_score_post::numeric::integer as possession_team_score_after_play,
    defteam_score_post::numeric::integer as defteam_score_after_play,
    score_differential_post::numeric::integer as score_differential_after_play,
    no_score_prob::numeric::numeric,
    opp_fg_prob::numeric::numeric,
    opp_safety_prob::numeric,
    opp_td_prob::numeric,
    fg_prob::numeric,
    safety_prob::numeric,
    td_prob::numeric,
    extra_point_prob::numeric,
    two_point_conversion_prob::numeric,
    ep::numeric as expected_points,
    epa::numeric as expected_points_average,
    total_home_epa::numeric,
    total_away_epa::numeric,
    total_home_rush_epa::numeric,
    total_away_rush_epa::numeric,
    total_home_pass_epa::numeric,
    total_away_pass_epa::numeric,
    air_epa::numeric,
    yac_epa::numeric,
    comp_air_epa::numeric,
    comp_yac_epa::numeric,
    total_home_comp_air_epa::numeric,
    total_away_comp_air_epa::numeric,
    total_home_comp_yac_epa::numeric,
    total_away_comp_yac_epa::numeric,
    total_home_raw_air_epa::numeric,
    total_away_raw_air_epa::numeric,
    total_home_raw_yac_epa::numeric,
    total_away_raw_yac_epa::numeric,
    wp::numeric,
    def_wp::numeric,
    home_wp::numeric,
    away_wp::numeric,
    wpa::numeric,
    vegas_wpa::numeric,
    vegas_home_wpa::numeric,
    home_wp_post,
    away_wp_post,
    vegas_wp::numeric,
    vegas_home_wp::numeric,
    total_home_rush_wpa::numeric,
    total_away_rush_wpa::numeric,
    total_home_pass_wpa::numeric,
    total_away_pass_wpa::numeric,
    air_wpa::numeric,
    yac_wpa::numeric,
    comp_air_wpa::numeric,
    comp_yac_wpa::numeric,
    total_home_comp_air_wpa::numeric,
    total_away_comp_air_wpa::numeric,
    total_home_comp_yac_wpa::numeric,
    total_away_comp_yac_wpa::numeric,
    total_home_raw_air_wpa::numeric,
    total_away_raw_air_wpa::numeric,
    total_home_raw_yac_wpa::numeric,
    total_away_raw_yac_wpa::numeric,
    punt_blocked::numeric::integer,
    first_down_rush::numeric::integer,
    first_down_pass::numeric::integer,
    first_down_penalty::numeric::integer,
    third_down_converted::numeric::integer,
    third_down_failed::numeric::integer,
    fourth_down_converted::numeric::integer,
    fourth_down_failed::numeric::integer,
    incomplete_pass::numeric::integer,
    touchback::numeric::integer,
    interception::numeric::integer,
    punt_inside_twenty::numeric::integer,
    punt_in_endzone::numeric::integer,
    punt_out_of_bounds::numeric::integer,
    punt_downed::numeric::integer,
    punt_fair_catch::numeric::integer,
    kickoff_inside_twenty::numeric::integer,
    kickoff_in_endzone::numeric::integer,
    kickoff_out_of_bounds::numeric::integer,
    kickoff_downed::numeric::integer,
    kickoff_fair_catch::numeric::integer,
    fumble_forced::numeric::integer,
    fumble_not_forced::numeric::integer,
    fumble_out_of_bounds::numeric::integer,
    solo_tackle::numeric::integer,
    "safety"::numeric::integer as is_safety,
    penalty::numeric::integer,
    tackled_for_loss::numeric::integer,
    fumble_lost::numeric::integer,
    own_kickoff_recovery::numeric::integer,
    own_kickoff_recovery_td::numeric::integer,
    qb_hit::numeric::integer,
    rush_attempt::numeric::integer,
    pass_attempt::numeric::integer,
    sack::numeric::integer,
    touchdown::numeric::integer,
    pass_touchdown::numeric::integer,
    rush_touchdown::numeric::integer,
    return_touchdown::numeric::integer,
    extra_point_attempt::numeric::integer,
    two_point_attempt::numeric::integer,
    field_goal_attempt::numeric::integer,
    kickoff_attempt::numeric::integer,
    punt_attempt::numeric::integer,
    fumble::numeric::integer,
    complete_pass::numeric::integer,
    assist_tackle::numeric::integer,
    lateral_reception::numeric::integer,
    lateral_rush::numeric::integer,
    lateral_return::numeric::integer,
    lateral_recovery::numeric::integer,
    passer_player_id,
    passer_player_name,
    passing_yards::numeric::integer,
    receiver_player_id,
    receiver_player_name,
    receiving_yards::numeric::integer,
    rusher_player_id,
    rusher_player_name,
    rushing_yards::numeric::integer,
    lateral_receiver_player_id,
    lateral_receiver_player_name,
    lateral_receiving_yards::numeric::integer,
    lateral_rusher_player_id,
    lateral_rusher_player_name,
    lateral_rushing_yards::numeric::integer,
    lateral_sack_player_id,
    lateral_sack_player_name,
    interception_player_id,
    interception_player_name,
    lateral_interception_player_id,
    lateral_interception_player_name,
    punt_returner_player_id,
    punt_returner_player_name,
    lateral_punt_returner_player_id,
    lateral_punt_returner_player_name,
    kickoff_returner_player_name,
    kickoff_returner_player_id,
    lateral_kickoff_returner_player_id,
    lateral_kickoff_returner_player_name,
    punter_player_id,
    punter_player_name,
    kicker_player_name,
    kicker_player_id,
    own_kickoff_recovery_player_id,
    own_kickoff_recovery_player_name,
    blocked_player_id,
    blocked_player_name,
    tackle_for_loss_1_player_id,
    tackle_for_loss_1_player_name,
    tackle_for_loss_2_player_id,
    tackle_for_loss_2_player_name,
    qb_hit_1_player_id,
    qb_hit_1_player_name,
    qb_hit_2_player_id,
    qb_hit_2_player_name,
    forced_fumble_player_1_team,
    forced_fumble_player_1_player_id,
    forced_fumble_player_1_player_name,
    forced_fumble_player_2_team,
    forced_fumble_player_2_player_id,
    forced_fumble_player_2_player_name,
    solo_tackle_1_team,
    solo_tackle_2_team,
    solo_tackle_1_player_id,
    solo_tackle_2_player_id,
    solo_tackle_1_player_name,
    solo_tackle_2_player_name,
    assist_tackle_1_player_id,
    assist_tackle_1_player_name,
    assist_tackle_1_team,
    assist_tackle_2_player_id,
    assist_tackle_2_player_name,
    assist_tackle_2_team,
    assist_tackle_3_player_id,
    assist_tackle_3_player_name,
    assist_tackle_3_team,
    assist_tackle_4_player_id,
    assist_tackle_4_player_name,
    assist_tackle_4_team,
    tackle_with_assist::numeric::integer,
    tackle_with_assist_1_player_id,
    tackle_with_assist_1_player_name,
    tackle_with_assist_1_team,
    tackle_with_assist_2_player_id,
    tackle_with_assist_2_player_name,
    tackle_with_assist_2_team,
    pass_defense_1_player_id,
    pass_defense_1_player_name,
    pass_defense_2_player_id,
    pass_defense_2_player_name,
    fumbled_1_team,
    fumbled_1_player_id,
    fumbled_1_player_name,
    fumbled_2_player_id,
    fumbled_2_player_name,
    fumbled_2_team,
    fumble_recovery_1_team,
    fumble_recovery_1_yards::numeric::integer,
    fumble_recovery_1_player_id,
    fumble_recovery_1_player_name,
    fumble_recovery_2_team,
    fumble_recovery_2_yards::numeric::integer,
    fumble_recovery_2_player_id,
    fumble_recovery_2_player_name,
    sack_player_id,
    sack_player_name,
    half_sack_1_player_id,
    half_sack_1_player_name,
    half_sack_2_player_id,
    half_sack_2_player_name,
    return_team,
    return_yards::numeric::integer,
    penalty_team,
    penalty_player_id,
    penalty_player_name,
    penalty_yards::numeric::integer,
    replay_or_challenge::numeric::integer,
    replay_or_challenge_result,
    penalty_type,
    defensive_two_point_attempt::numeric::integer,
    defensive_two_point_conv::numeric::integer,
    defensive_extra_point_attempt::numeric::integer,
    defensive_extra_point_conv::numeric::integer,
    safety_player_name,
    safety_player_id,
    season::numeric::integer,
    cp::numeric,
    cpoe::numeric,
    series::numeric::integer,
    series_success::numeric::integer,
    series_result,
    order_sequence::int,
    to_timestamp(start_time, 'MM/DD/YY, HH24:MI:SS') as kickoff_time,
    time_of_day::timestamptz,
    stadium,
    split_part(split_part(weather, ',', 1), ' Temp', 1) as weather_description,
    cast(
		case
			when weather like 'N/A (Indoors)%' or weather like '%Temp: Humidity:%' then null
			else split_part(split_part(weather, 'Temp: ', 2), '°', 1)
		end 
	as integer) as temperature_fahrenheit,
    cast(
		case 
			when weather like '%Humidity: Wind:%' then null
			else split_part(split_part(weather, 'Humidity: ', 2), '%', 1)
		end 
	as integer) as humidity_percent,
    split_part(weather, 'Wind: ' , 2) as wind_description,
    nfl_api_id,
    play_clock::numeric::integer as play_clock_time,
    play_deleted::numeric::integer,
    play_type_nfl,
    special_teams_play::numeric::integer,
    st_play_type as special_teams_play_type,
    end_clock_time,
    end_yard_line,
    fixed_drive::numeric::integer,
    fixed_drive_result,
    drive_real_start_time::timestamptz,
    drive_play_count::numeric::integer,
    drive_time_of_possession,
    drive_first_downs::numeric::integer,
    drive_inside20::numeric::integer,
    drive_ended_with_score::numeric::integer,
    drive_quarter_start::numeric::integer,
    drive_quarter_end::numeric::integer,
    drive_yards_penalized::numeric::integer,
    drive_start_transition,
    drive_end_transition,
    drive_game_clock_start,
    drive_game_clock_end,
    drive_start_yard_line,
    drive_end_yard_line,
    drive_play_id_started,
    drive_play_id_ended,
    away_score::numeric::integer,
    home_score::numeric::integer,
    case when location = 'NEUTRAL' then 1 else 0 end as neutral_site, 
    result::numeric::integer as net_score_relative_to_home_team,
    total::numeric::integer as total_points_scored,
    spread_line::numeric,
    total_line::numeric,
    div_game::numeric::integer as division_game,
    roof as roof_description,
    case
        when surface = 'grass ' then 'grass'
        when surface = 'a_turf' then 'astroturf'
        when surface = '' and stadium_id not in ('GER00', 'LON00', 'LON02', 'MEX00') then (select surface from raw.pbp r1 where r1.stadium_id = stadium_id limit 1)
        when surface = '' and stadium_id in ('GER00', 'LON00', 'LON02', 'MEX00') then 'international'
        else surface
    end as surface_description,
    temp::numeric::integer as temp_f,
    wind::numeric::integer as wind_mph,
    home_coach,
    away_coach,
    stadium_id,
    game_stadium,
    aborted_play::numeric::integer,
    success::numeric::integer as play_result_greater_than_epa,
    passer,
    passer_jersey_number::numeric::integer,
    rusher,
    rusher_jersey_number::numeric::integer,
    receiver,
    receiver_jersey_number::numeric::integer,
    pass::numeric::integer,
    rush::numeric::integer,
    first_down::numeric::integer,
    special::numeric::integer,
    play::numeric::integer,
    passer_id,
    rusher_id,
    receiver_id,
    name,
    jersey_number::numeric::integer,
    id,
    fantasy_player_name,
    fantasy_player_id,
    fantasy,
    fantasy_id,
    out_of_bounds::numeric::integer,
    home_opening_kickoff::numeric::integer,
    qb_epa::numeric,
    xyac_epa::numeric,
    xyac_mean_yardage::numeric,
    xyac_median_yardage::numeric,
    xyac_success::numeric,
    xyac_fd::numeric,
    xpass::numeric,
    pass_oe::numeric
from {{ source('warehouse', 'pbp') }}